repositories:
  - name: jetstack
    url: https://charts.jetstack.io
---
releases:
  # pihole
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.19.2
    values:
      - ./cert-manager.values.yaml