apiVersion: v1
kind: Namespace
metadata:
  name: obsidian
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: obsidian
spec:
  type: ClusterIP
  selector:
    app: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: 5984
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: obsidian
spec:
  serviceName: couchdb
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      securityContext:
        fsGroup: 100
      containers:
        - name: couchdb
          image: couchdb:3.3.3
          ports:
            - name: http
              containerPort: 5984
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-auth
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-auth
                  key: COUCHDB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /opt/couchdb
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi