repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    version: 41.6.0
    values:
      - values.traefik.yaml