---
DNS1:
  8.8.8.8
DNS2:
  1.1.1.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: false
serviceWeb:
  type: ClusterIP
serviceDns:
  loadBalancerIP: 192.168.1.221
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1