apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.homelab.redback.dev
  name: oauth2-proxy
  namespace: traefik-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`oauth.homelab.redback.dev`)
    services:
    - name: oauth2-proxy
      namespace: traefik-system
      port: 80
    middlewares:
    - name: auth-headers
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.homelab.redback.dev
  name: oauth2-route
  namespace: traefik-system
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`{subdomain:[a-z0-9-]+}.homelab.redback.dev`) && PathPrefix(`/oauth2/`)
    priority: 10000
    middlewares:
    - name: auth-headers
    services:
    - name: oauth2-proxy
      namespace: traefik-system
      port: 80
  tls: {}
