apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian-livesync
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`obsidian.homelab.redback.dev`)
      kind: Rule
      services:
        - name: couchdb-couchdb
          namespace: obsidian
          port: 5984
  tls: {}